#!/bin/bash
# A simple bash script to make building plugins
# (and copying them outside of the container) easier.
if [ -z "$1" ]; then
    echo "Plugin name to build required. Please choose from the following plugins:"
    ls /src/plugins
    exit
fi

plugin_index="/app/DuetWebControl/src/plugins/index.original.js"
plugin_index_dest="/app/DuetWebControl/src/plugins/index.js"
rm -rf $plugin_index_dest
ln -s $plugin_index $plugin_index_dest

rm -rf /app/DuetWebControl/vue.config.js && ln -s /app/DuetWebControl/vue.config.original.js /app/DuetWebControl/vue.config.js
npm run build-plugin "/src/plugins/$1"
plugin_file=`find . -name "$1-*.zip" | head -n 1`
mv "$plugin_file" "/src/plugins"